module.exports = {
	"agentRequestSubmitted": "Your request submitted",
	"agentAlreadyRequested": "Your request is under process",
	"agentRequestFailed": "Unable to process request",
	"giftBuySuccess": "Gift Bought Successfully",
	"giftBuyFailed": "Unable to process request",
	"getItemsSuccess": "Items found Successfully",
	"getItemsFailed": "Unable to process request",
	"removeItemsSuccess": "Items removed Successfully",
	"removeItemsFailed": "Unable to process request",
	"gitfImageIdUpdateSuccess": "Gift updated Successfully",
	"gitfImageIdUpdateFailed": "Unable to process request",
	"diceChipsUpdatSuccess": "Dice chips updated Successfully",
	"diceChipsUpdateFailed": "Unable to process request",
	"BuddyDataMissing": 'Data is missing',
	"BuddyFailed": 'Unable to process request',
	"BuddyUserIdMissing": "User Id is missing",
	"BuddyFriendIdMissing": "Friend Id is missing",
	"addBuddySendingToSelf": 'Can not send to self',
	"addBuddySuccess": 'Send Buddy Request successFully',
	"accptBuddySuccess": "Friend request accepted successfully",
	"rejectBuddySuccess": "Friend request declined successfully",
	"listBuddyNotFound": "No friends found",
	"listBuddySuccess": "Friends list find successfully",
	"sendChipsBuddyChipsMissing": "Chips is missing",
	"sendChipsBuddyNotFriend": "You are not friends",
	"sendChipsBuddyInsufficientChips": "You have insufficient chips",
	"transferBuddyChipsSuccess": "Chips Transfer Successfully",
	"pinDataMissing": "Data is missing",
	"pinUserIdMissing": "User Id is missing",
	"pinPinCodeMissing": "Pin Code is missing",
	"pinEmailMissing": "Email is missing",
	"pinUserNotFound": "User not foud",
	"pinUserNotHavePin": "User does not have pin code",
	"pinFailed": "Unable to process request",
	"pinUserFound": "User found",
	"createPinUserNotFound": "User not foud",
	"createPinAlreadyHavePin": "User alredy have pin code",
	"createPinEnterDiffEmail": "You need to enter a different email",
	"createPinSuccess": "Pin Code Create Successfully",
	"updatePinNewPinMissin": "New Pin Code is missing",
	"updatePinWrongPin": "Wrong Pin Code Entered",
	"updatePinSuccess": "Pin Code Update Successfully",
	"removePinWrongPassword": "Wrong Password Entered",
	"removePinSuccess": "Pin Code Remove Successfully",
	"verifyPinSuccess": "Pin Code Verify Successfully",
	"forgetPinSuccess": "Reset token send on your email",
	"forgetPinUserNotHaveEmail": "User does not have email",
}